//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_Flight1 p_Flight1;
        
        public static SteamVR_Input_ActionSet_Flight1 Flight1
        {
            get
            {
                return SteamVR_Actions.p_Flight1.GetCopy<SteamVR_Input_ActionSet_Flight1>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_Flight1 = ((SteamVR_Input_ActionSet_Flight1)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_Flight1>("/actions/Flight1")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.Flight1};
        }
    }
}
