//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Flight1 : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Accelerate
        {
            get
            {
                return SteamVR_Actions.flight1_Accelerate;
            }
        }
        
        public virtual SteamVR_Action_Boolean Fire
        {
            get
            {
                return SteamVR_Actions.flight1_Fire;
            }
        }
        
        public virtual SteamVR_Action_Boolean Recenter_Headset_Zero
        {
            get
            {
                return SteamVR_Actions.flight1_Recenter_Headset_Zero;
            }
        }
        
        public virtual SteamVR_Action_Boolean Decelerate
        {
            get
            {
                return SteamVR_Actions.flight1_Decelerate;
            }
        }
    }
}
